### ISSUE TITLE
mach fails with error on non-existent classpath dir

### ISSUE THREAD

**Issue by stijnopheide** [juxt/mach#55]
**minimal Machfile.edn to reproduce the error**
```
{mach/dependencies [[aero "1.1.2"]]
 hello (println "Hello")}
```
**error**
```
Writing Mach classpath to .mach/cp
evalmachine.<anonymous>:98
throw ex;
^

Error: ENOENT: no such file or directory, open '.mach/cp'
    at Object.fs.openSync (fs.js:652:18)
    at fs.readFileSync (fs.js:553:33)
    at evalmachine.<anonymous>:4299:43
    at evalmachine.<anonymous>:4346:43
    at mach$core$preprocess_dependencies_$_state_machine__4__auto____1 (evalmachine.<anonymous>:4367:4)
    at mach$core$preprocess_dependencies_$_state_machine__4__auto__ (evalmachine.<anonymous>:4383:72)
    at cljs$core$async$impl$ioc_helpers$run_state_machine (evalmachine.<anonymous>:90:74)
    at cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped (evalmachine.<anonymous>:93:63)
    at evalmachine.<anonymous>:4398:67
    at Immediate.cljs$core$async$impl$dispatch$process_messages [as _onImmediate] (evalmachine.<anonymous>:16:6)
```

**versions**
- node 8.7.0
- mach 1.4.7
- lumo 0.20.6

This is on OS X Sierra.

**Comment by mantree** [comment]
Just bumped into this on a new install. Did you manage to get his moving at all?

**Comment by mantree** [comment]
Not entirely sure what i did, but a new terminal seemed to help.

**Comment by stijnopheide** [comment]
In the meantime, I've had the same issue on Arch Linux. Some fiddling around with node and lumo versions and then suddenly it works, but I can't remember what exactly solved it.

**Comment by mantree** [comment]
I'm on Arch and that pretty much sums up what did... Next time I'm starting over I'll take better notes.
