### ISSUE TITLE
npm install examples broken

### ISSUE THREAD

**Issue by RickMoynihan** [juxt/mach#57]
This could well be my `lumo`/`npm` installation, but after checking out mach:

```
$ cd examples/npm-left-pad
$ mach pad-foo
npm installing left-pad 1.1.3
evalmachine.<anonymous>:98
throw ex;
^

Error: Cannot find module 'left-pad'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:8:15
    at evalmachine.<anonymous>:32:43
    at cljs$user$state_machine__4__auto____1 (evalmachine.<anonymous>:53:4)
    at cljs$user$state_machine__4__auto__ (evalmachine.<anonymous>:69:46)
    at cljs$core$async$impl$ioc_helpers$run_state_machine (evalmachine.<anonymous>:90:74)
    at cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped (evalmachine.<anonymous>:93:63)
```

lumo/npm versions:

```
Lumo 1.8.0-beta
ClojureScript 1.9.927
Node.js v8.5.0
```

**Comment by RickMoynihan** [comment]
I've noticed if I do:

```
$ npm install left-pad
+ left-pad@1.2.0
added 1 package in 1.45s
```

Then it appears to work.

```
$ mach pad-foo
npm installing left-pad 1.1.3
  foo
```

Is this expected?
